[platformio]
src_dir = firmware

[env:adafruit_feather_nrf52840_sense]
platform = nordicnrf52
board = adafruit_feather_nrf52840_sense
framework = arduino

platform_packages =
   framework-arduinoadafruitnrf52 @ https://github.com/devicefuture/Adafruit_nRF52_Arduino.git

build_flags =
   -DNRF52_S132